name: todo-cli
base: core24
version: 1.0.1
summary: todo command-line app
description: If you want to get it done, first write it down.

grade: stable
confinement: strict

parts:
  todo-cli:
    plugin: dump
    source: https://github.com/sirekanian/todo/releases/download/v$SNAPCRAFT_PROJECT_VERSION/todo-linux-$CRAFT_ARCH_BUILD_FOR-$SNAPCRAFT_PROJECT_VERSION.tar.gz

apps:
  todo-cli:
    command: todo
